### ISSUE TITLE
CHOLMOD version incompatibility?

### ISSUE THREAD

**Issue by Niohuruzh** [IGS/FADU#15]
Hi
Is there any problem when CHOLMOD version incompatibility?

> `┌ Warning: CHOLMOD version incompatibility
> │ 
> │ Julia was compiled with CHOLMOD version 4.0.4. It is
> │ currently linked with version 5.3.0.
> │ This might cause Julia to terminate when working with
> │ sparse matrix factorizations, e.g. solving systems of
> │ equations with \.
> │ 
> │ It is recommended that you use Julia with the same major
> │ version of CHOLMOD as the one used during the build, or
> │ download the generic binaries from www.julialang.org,
> │ which ship with the correct versions of all dependencies.
> └ @ SparseArrays.CHOLMOD ~/share/julia/stdlib/v1.10/SparseArrays/src/solvers/cholmod.jl:206`
> 

And there is little different result compared to Example command result. Here is my result:

> featureID	uniq_len	num_alignments	counts	tpm
cds0	1017	4.5	2.81	1755.54
cds1	1194	3.5	2.48	1318.88

**Comment by adkinsrs** [comment]
@Niohuruzh, how was your version of Julia installed?  Did you perform the installation or was this done by a sysadmin?  

It seems like only the TPM values between your example and the documentation example are slightly off. I did some research, and CHOLMOD seems to be a SparseArrays-related module file which FADU does not use, at least not directly.  Can you paste your package versions (open the REPL, hit "]", then type in "status" and hit Enter).  I personally do not have the SparseArrays.jl packagin installed.

**Comment by Niohuruzh** [comment]
Hi,
Thanks for your reply.
Julia(Version 1.10.3) is installed by conda.

> [c7e460c6] ArgParse v1.2.0
> [8e4a8c10] BED v0.3.0
> [28d598bf] BGZFStreams v0.3.2
> [af1dc308] GFF3 v0.2.3
> [899a7d2d] GenomicFeatures v2.1.0
> [4ffb77ac] Indexes v0.1.3
> [09ab397b] StructArrays v0.6.18
> [d759349c] XAM v0.3.1
> [56ddb016] Logging

**Comment by Niohuruzh** [comment]
Thank you! It seems that my installed FADU is working correctly.
