### ISSUE TITLE
A very long run time

### ISSUE THREAD

**Issue by Xiaojun928** [IGS/FADU#5]
Hi,

I used the default mode and one thread to quantify expression based on a batch of samples with 1.5~10M read pairs, but the running time seems not to depend on the number of read pairs. Samples with over 5M pairs can be finished within two days, while some samples with less than 2M pairs have not finished after four days. 

The paper showed that the maximum running time of FADU was not over 4000s. I also tried multiple threads, but it has run over 4000s and not finished yet.
Do you think it's normal in my case? Could you please give me some suggestions to speed the fadu up?

Thanks a lot!

**Comment by Xiaojun928** [comment]
Hi, 

The last input bam file was generated by hisat2, and the running time is over 10 days. 
I also tried the bwa to generate the bam files, the fadu finished in several minutes.  More wired is that the fadu results (attached files, I extracted top 500 genes) of two methods are very different for the same gene. Which one should be used for the following analyses? Do you have any idea about why the quantification varies so much?

Looking for your reply and thanks a lot!
[bwa-fadu.txt](https://github.com/IGS/FADU/files/6679882/bwa-fadu.txt)
[hisat2-fadu.txt](https://github.com/IGS/FADU/files/6679883/hisat2-fadu.txt)

**Comment by adkinsrs** [comment]
@Xiaojun928 I apologize for my delayed response to this.  Without knowing the timing of the individual steps that you ran, I believe that that EM iteration step may be the bottleneck, as this step tends to go slower when there are more multimapped reads present. It could be that your 5M-pair sample has much fewer multimapped reads compared to the 2M-pair samples.  

Also, with regards to threading, the initial processing takes advantage of threading code written in the BioJulia XAM.jl module. Unfortunately I could not utilize that same code for the EM iteration processing step, and so only a small portion of that step has threading.  I would like to eventually improve that though.

**Comment by adkinsrs** [comment]
Closing as stale issue
