### ISSUE TITLE
Import FADU results into DESeq2 when counts are not integers

### ISSUE THREAD

**Issue by sixvable** [IGS/FADU#7]
Really glad we have a gene quantification tool designed for prokaryotic RNA-seq finally! 👍 

But how should I import FADU results into DESeq2 if the counts number are **NOT** integers? 😕  **Salmon** way or just using R function `round()`?

**Comment by adkinsrs** [comment]
I think using R's `round()` should be perfectly fine, unless the largest counts were in the single or double-digit range where rounding out the decimal point would have a much greater influence.

**Comment by adkinsrs** [comment]
@matt-chung do you have any thoughts?

**Comment by sixvable** [comment]
Thanks for the reply! 😄 
 
> I think using R's `round()` should be perfectly fine, unless the largest counts were in the single or double-digit range where rounding out the decimal point would have a much greater influence.

I just found **Salmon/tximport** way also use `round()` functions internally!

But I have a gut feeling that **Salmon/tximport** way might be more suitable since it would considering genes/transcripts length as the *normalization factors* which FADU might also provide as **uniq_len** in output results.
