### ISSUE TITLE
ERROR: LoadError: Attempted to find index file for BAM file /home/ofm/Documents/Genomics/Ecoli/FADU_input/c_1.sorted.bam but could not find one

### ISSUE THREAD

**Issue by ofleitas** [IGS/FADU#8]
Hello 

I am to trying run FADU with a sample but I am gettin this error 

(base) ofm@ofm-Aspire-E5-571G:~/src/FADU$ julia ./fadu.jl -M -g "/home/ofm/Documents/Genomics/Ecoli/genome/GCF_000026545.1_ASM2654v1_genomic.gff" -b "/home/ofm/Documents/Genomics/Ecoli/FADU_input/c_1.sorted.bam" -o "/home/ofm/Documents/Genomics/Ecoli/FADU_output/" -s "no" -f "gene" -a "ID" -p
[ Info: Parsed args:
[ Info:   bam_file  =>  /home/ofm/Documents/Genomics/Ecoli/FADU_input/c_1.sorted.bam
[ Info:   gff3_file  =>  /home/ofm/Documents/Genomics/Ecoli/genome/GCF_000026545.1_ASM2654v1_genomic.gff
[ Info:   stranded  =>  no
[ Info:   attribute_type  =>  ID
[ Info:   pp_only  =>  true
[ Info:   max_fragment_size  =>  1000
[ Info:   rm_multimap  =>  true
[ Info:   output_dir  =>  /home/ofm/Documents/Genomics/Ecoli/FADU_output/
[ Info:   em_iter  =>  1
[ Info:   feature_type  =>  gene
[ Info: Processing annotation features...
[ Info: Getting unique coordinates per contig and feature...
[ Info: Initializing dictionary of feature count information
ERROR: LoadError: Attempted to find index file for BAM file /home/ofm/Documents/Genomics/Ecoli/FADU_input/c_1.sorted.bam but could not find one
Stacktrace:
 [1] error(s::String)
   @ Base ./error.jl:35
 [2] main()
   @ Main ~/src/FADU/fadu.jl:147
 [3] top-level scope
   @ ~/src/FADU/fadu.jl:206
in expression starting at /home/ofm/src/FADU/fadu.jl:206
(base) ofm@ofm-Aspire-E5-571G:~/src/FADU$ 

Any suggestion?
Thank you in advance

**Comment by adkinsrs** [comment]
Hi @ofleitas 

In the directory where your BAM file is housed, is there a "c_1.sorted.bam.bai" file in the same directory?  The BAM input file must be accompanied by its corresponding index file.

**Comment by ofleitas** [comment]
Hello 

Inicially the c_1.sorted.bam.bai file was not in the same directory. Now I put both together in the same directory but I got error again 

ofm@ofm-Aspire-E5-571G:~/src/FADU$ julia ./fadu.jl -M -g "/home/ofm/Documents/Genomics/Ecoli/FADU_input/GCF_000026545.1_ASM2654v1_genomic.gff" -b " /home/ofm/Documents/Genomics/Ecoli/FADU_input/c_1.sorted.bam" -o "/home/ofm/Documents/Genomics/Ecoli/FADU_output/" -s "no" -f "gene" -a "ID" -p
[ Info: Parsed args:
[ Info:   bam_file  =>   /home/ofm/Documents/Genomics/Ecoli/FADU_input/c_1.sorted.bam
[ Info:   gff3_file  =>  /home/ofm/Documents/Genomics/Ecoli/FADU_input/GCF_000026545.1_ASM2654v1_genomic.gff
[ Info:   stranded  =>  no
[ Info:   attribute_type  =>  ID
[ Info:   pp_only  =>  true
[ Info:   max_fragment_size  =>  1000
[ Info:   rm_multimap  =>  true
[ Info:   output_dir  =>  /home/ofm/Documents/Genomics/Ecoli/FADU_output/
[ Info:   em_iter  =>  1
[ Info:   feature_type  =>  gene
[ Info: Processing annotation features...
[ Info: Getting unique coordinates per contig and feature...
[ Info: Initializing dictionary of feature count information
ERROR: LoadError: Attempted to find index file for BAM file  /home/ofm/Documents/Genomics/Ecoli/FADU_input/c_1.sorted.bam but could not find one
Stacktrace:
 [1] error(s::String)
   @ Base ./error.jl:35
 [2] main()
   @ Main ~/src/FADU/fadu.jl:147
 [3] top-level scope
   @ ~/src/FADU/fadu.jl:206
in expression starting at /home/ofm/src/FADU/fadu.jl:206

**Comment by adkinsrs** [comment]
I looked at the code and I believe I see the issue.

I only coded it to look for something like c_1.sorted.bai, not c_1.sorted.bam.bai ... I will modify it soon to consider both cases.  In the meantime if you rename your BAM index file to c_1.sorted.bai, it should run

**Comment by ofleitas** [comment]
Hello

It worked. Thank you very much .
